import { Common } from '../common';
import { IResourceContext } from '../utils/ResourceContext';
import { IAchievementIcon } from './AchievementIcon.class';

const ENDPT = 'achievementicons';

/**
 * Achievement icons resource
 */
export class AchievementIconsResource {
    private common: Common<IAchievementIcon>;
    private context: IResourceContext;

    /**
     * Construct the achievement icons resource
     * @param context The context to make requests as
     */
    constructor(context: IResourceContext) {
        this.context = context;
        this.common = new Common(context, ENDPT);
    }

    /**
     * Get all achievement icons
     * @param userOpts option overrides for this request
     * @returns A promise that resolves to an array of achievement icon identifiers
     */
    public getAll(userOpts?): Promise<IAchievementIcon[]> {
        return this.context.http.makeRequest({
            method: 'GET',
            url: `/v1/apps/${this.context.applicationId}/${ENDPT}`
        }, userOpts);
    }

    /**
     * Delete previously uploaded achievement icon by filename.
     * @param iconFileName icon file name (generated by BadgeUp when the icon was uploaded, not the original file name)
     * @param userOpts option overrides for this request
     * @returns A promise that resolves to the deleted achievement icon
     */
    public remove(iconFileName: string, userOpts?): Promise<IAchievementIcon> {
        return this.common.remove(iconFileName, userOpts);
    }
}
